# ---------------------------------------------------------------------------- #
# Site configuration
# ---------------------------------------------------------------------------- #
site="FS1_example"
tz='UTC'
lat=-47.308069
lon=66.984374

# ---------------------------------------------------------------------------- #
# Level-0 to Level-1
# ---------------------------------------------------------------------------- #
[level0_1]
skiprows=[0,2,3]
header=0
index_col='TIMESTAMP'
na_values=['NAN']
udg_key='TCDT'
sep=','


# ---------------------------------------------------------------------------- #
# Level-1 to Level-2
# ---------------------------------------------------------------------------- #
[level1_2]

# Distance from bottom of UDG rim to surface
# Add a new row when UDG position changes (e.g. pole extension).
udg_to_surface=[[2021-04-30, 2.06], [2021-05-02T22:00:00, 1.81]]

# Columns in Level-1 that should be removed from Level-2.
remove_columns=["RECORD", "PTemp_C_Min", "DT"]

# Installation date, depth (-ve) of installed TDRs. 
[level1_2.tdr_info]
1=[2021-04-30,-0.48]
2=[2021-04-30,-1.15]
3=[2021-04-30,-1.36]

# DAT files containing sensor positions, first sensor, depth of first sensor
[level1_2.dtc_info]
1=[2021-04-30, "fielddata_202107/FS1_DTC1_DiagSettings.dat", 1, -0.17]

[level1_2.ec_info]
# Date, number, depth of first sensor in borehole (-ve if below surface).
1=[2021-04-30, "EC_1.65m.csv", 1, -0.16]


# ---------------------------------------------------------------------------- #
# Level-0 datasets
# You may override [level0_1] options in here on a per-dataset basis.
# ---------------------------------------------------------------------------- #
[level0]
[level0.fielddata_202107]
subpath=""
type="bales"
bales_start=1
bales_stop=3

    
